apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clickhouse
  name: clickhouse
  namespace: log
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - image: clickhouse/clickhouse-server
        imagePullPolicy: IfNotPresent
        name: clickhouse
        ports:
        - containerPort: 8123
          protocol: TCP
        resources:
          limits:
            cpu: 1048m
            memory: 2Gi
          requests:
            cpu: 1048m
            memory: 2Gi
        volumeMounts:
        - mountPath: /etc/clickhouse-server/users.d/default-password.xml
          subPath: default-password.xml
          name: default-password
      volumes:
      - name: default-password
        configMap:
          name: default-password
          defaultMode: 511
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: log
spec:
  ports:
  - port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: clickhouse
  type: ClusterIP

