apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-echo-v1
  namespace: udp-demo
  labels:
    app: udp-echo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-echo
      version: v1
  template:
    metadata:
      labels:
        app: udp-echo
        version: v1
    spec:
      serviceAccountName: udp-echo
      containers:
        - name: udp-echo-server
          image: "cybwan/fsm-demo-udp-echo-server:latest"
          imagePullPolicy: Always
          command: ["/udp-echo-server"]
          args: [ "--port", "6000" ]
          ports:
            - containerPort: 6000
              name: udp-echo-server
              protocol: UDP
