#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: bookbuyer
#  namespace: bookbuyer
#  labels:
#    app: bookbuyer
#spec:
#  ports:
#    - port: 20880
#      name: tcp-dubbo-port
#  selector:
#    app: bookbuyer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookbuyer
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookbuyer
      version: v1
  template:
    metadata:
      labels:
        app: bookbuyer
        version: v1
    spec:
      containers:
        - name: bookbuyer
          image: addozhang/bookbuyer-dubbo:0.3.1
          imagePullPolicy: Always
          ports:
            - containerPort: 20880
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'dubbo,prod'
            - name: IDENTITY
              value: bookbuyer
#            - name: DUBBO_REGISTRY_ADDRESS
#              value: 'zookeeper.default'
