#!make

LOCAL_REGISTRY ?= localhost:5000

define pull
    docker pull $(2)/$(1)
    docker tag $(2)/$(1) $(3)/$(1)
    docker push $(3)/$(1)
    docker rmi $(2)/$(1)
endef

.PHONY: pull-images
pull-images:
	$(call pull,consul:1.5.3,docker.io,localhost:5000)
	$(call pull,consul:1.15.4,docker.io,localhost:5000)
	$(call pull,flomesh/samples-discovery-server:latest,docker.io,localhost:5000)
	$(call pull,nacos/nacos-server:v2.3.0-slim,docker.io,localhost:5000)
	$(call pull,zookeeper:3.6.2,docker.io,localhost:5000)
	$(call pull,tobilg/zookeeper-webui:latest,docker.io,localhost:5000)
	$(call pull,cybwan/springboot-consul-demo:latest,docker.io,localhost:5000)
	$(call pull,cybwan/springboot-eureka-demo:latest,docker.io,localhost:5000)
	$(call pull,cybwan/springboot-nacos-demo:latest,docker.io,localhost:5000)
	$(call pull,cybwan/springboot-dubbo-demo:latest,docker.io,localhost:5000)
	$(call pull,cybwan/grpc-server:latest,docker.io,localhost:5000)
	$(call pull,cybwan/grpc-client:latest,docker.io,localhost:5000)

.PHONY: switch-images-to-local
switch-images-to-local:
	@cd manifests;find . -type f | xargs sed -i 's#image: consul#image: localhost:5000/consul#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: nacos#image: localhost:5000/nacos#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: flomesh#image: localhost:5000/flomesh#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: zookeeper#image: localhost:5000/zookeeper#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: tobilg#image: localhost:5000/tobilg#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: cybwan#image: localhost:5000/cybwan#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t consul#-t localhost:5000/consul#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t nacos#i-t localhost:5000/nacos#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t flomesh#-t localhost:5000/flomesh#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t zookeeper#-t localhost:5000/zookeeper#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t tobilg#-t localhost:5000/tobilg#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t cybwan#-t localhost:5000/cybwan#g'

.PHONY: switch-images-to-remote
switch-images-to-remote:
	@cd manifests;find . -type f | xargs sed -i 's#image: localhost:5000/consul#image: consul#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: localhost:5000/nacos#image: nacos#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: localhost:5000/flomesh#image: flomesh#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: localhost:5000/zookeeper#image: zookeeper#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: localhost:5000/tobilg#image: tobilg#g'
	@cd manifests;find . -type f | xargs sed -i 's#image: localhost:5000/cybwan#image: cybwan#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t localhost:5000/consul#-t consul#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t localhost:5000/nacos#-t nacos#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t localhost:5000/flomesh#-t flomesh#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t localhost:5000/zookeeper#-t zookeeper#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t localhost:5000/tobilg#-t tobilg#g'
	@cd scripts;find . -type f | xargs sed -i 's#-t localhost:5000/cybwan#-t cybwan#g'

.PHONY: local
local: switch-images-to-local

.PHONY: remote
remote: switch-images-to-remote

.PHONY: md2sh
md2sh:
	@find . -type f -name "scenarios.*.sh" -exec sed -i "s/\`\`\`/###/g" {} +
	@find . -type f -name "scenarios.*.sh" -exec sed -i "s/\*\*/##/g" {} +
