---
apiVersion: v1
kind: Service
metadata:
  name: flomesh-demo-c-svc
  labels:
    app: flomesh-demo-c
spec:
  selector:
    app: flomesh-demo-c
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP