apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      serviceAccountName: httpbin
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: flomesh/pipy-nightly:latest
        imagePullPolicy: IfNotPresent
        name: httpbin
        command:
          - pipy
          - -e
          - |
            pipy()
            .listen(8080)
            .serveHTTP(new Message({ status: 501 }))
        ports:
        - containerPort: 8080
