apiVersion: v1
kind: Service
metadata:
  name: sc-tiny
  labels:
    app: tiny
spec:
  ports:
  - name: app
    port: 9191
    protocol: TCP
    targetPort: 9191
  selector:
    app: sc-tiny
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-tiny
  labels:
    app: sc-tiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-tiny
  template:
    metadata:
      labels:
        app: sc-tiny
    spec:
      containers:
      - name: sc-tiny
        image: spurringworld/sc-tiny:0.0.1
        imagePullPolicy: IfNotPresent
