apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-demo
  template:
    metadata:
      labels:
        app: client-demo
    spec:
      serviceAccountName: client-demo
      containers:
      - name: client-demo
        image: spurringworld/tiny-client-demo:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: serverAddress
          value: "${server_demo_pod_ip}:8082"
        volumeMounts:
        - mountPath: /home/java/config
          name: javacfg
      volumes:
        - name: javacfg
          configMap:
            name: client-application-properties
            items:
              - key: "application.properties"
                path: "application.properties"

