---
apiVersion: v1
kind: Service
metadata:
  name: flomesh-demo-svc
  labels:
    app: flomesh-demo
spec:
  selector:
    app: flomesh-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
      nodePort: 30817
  type: NodePort