apiVersion: v1
kind: ConfigMap
metadata:
  name: flomesh-demo-b-configmap
  labels:
    app: flomesh-demo-b
data:
  # 配置文件内容
  application.yaml: |
    server:
      port: 8080
    spring:
      application:
        name: flomesh-demo-b
      cloud:
        nacos:
          discovery:
            server-addr: nacos.flomesh-test:8848
            metadata:
              organization: iflorens-test
              ha-service: true
          config:
            enabled: false
            refresh-enabled: false
    logging:
      level:
        org:
          springframework: DEBUG
    app:
      name: flomesh-demo-test-cm-hk