apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: cybwan/grpc-client
          imagePullPolicy: Always
          command: [ "java", "-jar", "grpc-client-1.0.0.jar" ]
        - name: curl
          image: cybwan/ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command: [ "sleep", "365d" ]