---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-curl-application-yml
data:
  application.yml: |
    spring:
      profiles:
        default:
          - "eureka"
      application:
        name: curl
    logging:
      level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    management:
      endpoints:
        web:
          exposure:
            include: "health,info,prometheus"
    dubbo:
      enabled: false #disable dubbo bootstrap in profiles other than dubbo
    ---
    # Prod Profile Configuration
    server:
      port: 14001
    spring:
      config:
        activate:
          on-profile: eureka
  application-eureka.yml: |
    eureka:
      client:
        registerWithEureka: true
        fetchRegistry: true
        gZipContent: false
      instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
    ---
    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka.default:8761/eureka/
    spring:
      config:
        activate:
          on-profile: eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${cluster}-curl
  labels:
    version: v1
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: curl
      version: v1
  template:
    metadata:
      labels:
        app: curl
        version: v1
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: "/actuator/prometheus"
          prometheus.io/port: "14001"
    spec:
      containers:
        - name: curl
          image: cybwan/springboot-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 14001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'eureka'
            - name: IDENTITY
              value: curl
            - name: EUREKA_INSTANCE_METADATAMAP_VERSION
              value: v1
            - name: JAVA_OPTS
              value: -Xms256M -Xmx512M
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:./opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=curl
          command: ['java']
          args: [
            "-Dotel.traces.exporter=none",
            "-Dotel.metrics.exporter=none",
            "-Dotel.propagators=tracecontext,baggage,b3multi",
            "-jar",
            "curl-eureka.jar",
          ]
          volumeMounts:
            - mountPath: /config
              name: javacfg
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: javacfg
          configMap:
            name: eureka-curl-application-yml
            items:
              - key: "application.yml"
                path: "application.yml"
              - key: "application-eureka.yml"
                path: "application-eureka.yml"