---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dubbo-curl-application-yml
data:
  application.yml: |
    spring:
      profiles:
        default:
          - "dubbo"
      application:
        name: curl
    logging:
      level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    management:
      endpoints:
        web:
          exposure:
            include: "health,info,prometheus"
    dubbo:
      enabled: false #disable dubbo bootstrap in profiles other than dubbo
    ---
    # Prod Profile Configuration
    server:
      port: 14001
    spring:
      config:
        activate:
          on-profile: dubbo
  application-dubbo.yml: |
    service:
      version:
        curl: v1
    dubbo:
      enabled: true
      scan:
        base-packages: io.flomesh.demo.simple.dubbo
      registry:
        address: zookeeper://zookeeper.default:2181
    grpc:
      server:
        port: -1 #disable grpc server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
      version: v1
  template:
    metadata:
      labels:
        app: curl
        version: v1
    spec:
      containers:
        - name: curl
          image: cybwan/springboot-dubbo-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 14001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'dubbo'
            - name: IDENTITY
              value: curl
            - name: JAVA_OPTS
              value: -Xms256M -Xmx512M
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:./opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=curl
          command: ['java']
          args: [
            "-Dotel.traces.exporter=none",
            "-Dotel.metrics.exporter=none",
            "-Dotel.propagators=tracecontext,baggage,b3multi",
            "-jar",
            "curl-dubbo.jar",
          ]
          volumeMounts:
            - mountPath: /config
              name: javacfg
      volumes:
        - name: javacfg
          configMap:
            name: dubbo-curl-application-yml
            items:
              - key: "application.yml"
                path: "application.yml"
              - key: "application-dubbo.yml"
                path: "application-dubbo.yml"